### ISSUE TITLE
Not working when added via Cocoapod dynamic framework

### ISSUE THREAD

**Issue by kapoorsahil** [aschuch/StatefulViewController#12]

**Comment by aschuch** [comment]
What exactly does not work like you expected?

**Comment by kapoorsahil** [comment]
It's giving 'does not confirm to protocol StatefulViewController' and 'does not confirm to protocol BackingViewProvider'. I think it is not recognizing the functions defined in implementation file. 

Example is also giving same error when using cocoapod rather than manually pasting library.

**Comment by aschuch** [comment]
You are using the swift2 branch right? How does your Podfile look like?
I haven't had the chance to test that with Cocoapods yet, there might be some errors.

**Comment by kapoorsahil** [comment]
source 'https://github.com/CocoaPods/Specs'

    platform :ios, '8.0'
    use_frameworks! 
    inhibit_all_warnings!
    target 'MyApp' do

    pod ;StatefulViewController', :git => 
    end

**Comment by aschuch** [comment]
Podfile looks good to me.

Are you following the [new README](https://github.com/aschuch/StatefulViewController/blob/swift2/README.md) to integrate StatefulViewController?
Your view controller now needs to inherit from e.g. `UIViewController`.

```swift
class X: UIViewController, StatefulViewController {
}
```

**Comment by kapoorsahil** [comment]
Yes, I am doing exactly the same as in your Swift2 example. I integrated manually and it's working fine.

**Comment by aschuch** [comment]
Could you please try with the official `1.0` version, which includes Swift 2 support?

**Comment by kapoorsahil** [comment]
Still the same error when using via cocoapod.

**Comment by aschuch** [comment]
I have just found the issue, please check again. This should be working now.

**Comment by aschuch** [comment]
Still dependent on CocoaPods/Specs#13568 for the podspec to be updated.
