### ISSUE TITLE
Why minimum platform version is set to iOS8 ?

### ISSUE THREAD

**Issue by IsaacSee** [aschuch/StatefulViewController#14]
We plan on using your nice component on a project but we are compatible to iOS 7 and above.
Is there a complex issue in the current implementation preventing from using it on iOS7 ? Or is it just the cocoapod specs ?

**Comment by aschuch** [comment]
Hi, I am personally not working with iOS 7 anymore, thus cannot provide support for any issues that might come up due to that legacy.
The code itself is not specific to iOS >= 8 as far as I know, feel free to fork and try lowering the minimum version to iOS 7 and it should work just fine.
