### ISSUE TITLE
Set a different frame in the loading View does not work

### ISSUE THREAD

**Issue by LucianoTurrini** [aschuch/StatefulViewController#17]
Thanks for this really great library!

I have a problem:

I can not put a different frame for LoadingView, for example:

loadingView = UIView (frame: CGRectMake (0, 0, 100, 100))

this does not work, the loadingView always frame the superview, never changes, can help me?

**Comment by LucianoTurrini** [comment]
![screen shot 2016-01-20 at 11 03 28 pm](https://cloud.githubusercontent.com/assets/10828312/12468368/10606784-bfca-11e5-968d-abc5694d173b.png)

**Comment by aschuch** [comment]
Yes, the placeholder views are always fixed to the edges of the screen at the moment. 
I am open for discussion to change that.

For now, if you want to show the content behind the placeholder view, you could make parts of the view transparent.

**Comment by aschuch** [comment]
This has been addressed in #23
