### ISSUE TITLE
No Objective C Version ?

### ISSUE THREAD

**Issue by iamabhiee** [aschuch/StatefulViewController#2]
Swift Only? 
No Objective-C Version ?

**Comment by srikanthpandeti** [comment]
i also need a Objective-C Version of this

**Comment by aschuch** [comment]
I have no plans to support Objective-C. However, you can use Swift with Objective-C:
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by bxyfighting** [comment]
Objective-C Version: https://github.com/bxyfighting/BXYStatefulViewController
