### ISSUE TITLE
tvOS

### ISSUE THREAD

**Issue by yonaskolb** [aschuch/StatefulViewController#25]
Hi

Would you be able to push a new release to cocoapods, so the tvOS changes in the podspec come through?

**Comment by mzeeshanid** [comment]
Facing the similar issue on tvOS:

> The platform of the target `Target-TV` (tvOS 9.0) is not compatible with `StatefulViewController (1.0)`, which does not support `tvos`.

**Comment by aschuch** [comment]
I have just pushed a new release for 1.1. Enjoy!
