### ISSUE TITLE
Where is the StatefulPlaceholderView-PR?

### ISSUE THREAD

**Issue by AFcgi** [aschuch/StatefulViewController#28]
I couldn't find the <code>StatefulPlaceholderView</code> protocol in your current version 1.1.0. Where is it?

**Comment by douglasd3** [comment]
Same issue here

**Comment by aschuch** [comment]
I have just added a new 1.2 release that includes the latest changes. Let me know if that works for you. 🎉

**Comment by aschuch** [comment]
@AFcgi @douglasd3 I am closing this issue, if you have any further questions do not hesitate to ask.
