### ISSUE TITLE
Swift 3 pod version

### ISSUE THREAD

**Issue by AnthonyMDev** [aschuch/StatefulViewController#35]
It would be really great if we could get a Swift 3 version pushed to the CocoaPods master spec repo soon.

Thank you!

**Comment by aschuch** [comment]
I've just pushed a recent Podspec for Swift 2.3.
I still want to wait for a few more people to test everything on 3.0 and will make a new tagged release soon.

**Comment by AnthonyMDev** [comment]
Okay thanks!

**Comment by AnthonyMDev** [comment]
It seems that there is one build error for Swift 3 on your swift 3 branch. 

`ViewStateMachine` line 200:
`@escaping may only be applies to parameters of function type`

Super quick fix. I'll be converting my application today and doing some testing. I'll report back if the Swift 3 version works right for me!

**Comment by aschuch** [comment]
Yes, the Swift 3 branch is not fully up to date. Please refer directly to master, where this is actually fixed.

**Comment by AnthonyMDev** [comment]
Any idea when we will have a release for this yet?

**Comment by JettF** [comment]
Any word on the 3.0 release yet?

**Comment by AnthonyMDev** [comment]
@aschuch Are you still actively maintaining this library? Having an official version pushed for swift 3.0 would be really helpful. It would also be really great to have PR #29 merged for the new version.

If you don't have the time to maintain this currently, I'd be happy to help out as a contributor if you are willing. I have plenty of experience maintaining open source projects and working the the CocoaPods `pod trunk`.

If there isn't an update on this library sometime soon, I'm going to have to release a new pod from my fork for this repository. I'd really hate to have to do that though. Please advise. Thanks.

**Comment by aschuch** [comment]
@AnthonyMDev  I do not have a lot of time for OSS at the moment, unfortunately. 
I've just pushed version 3.0 to Cocoapods trunk.
(I could not merge your changes in #29 since they are not ready for Swift 3.0 yet, sorry).

**Comment by AnthonyMDev** [comment]
I totally understand your struggles. We've all been there. Thanks so much for pushing a version. 

When I get some time, I'll update #29 for Swift 3 and notify you.

**Comment by aschuch** [comment]
Thanks <3
