### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by russellyi** [aschuch/StatefulViewController#37]
`carthage version`: 0.16.2
`xcodebuild -version`: Xcode 8.0  Build version 8A218a

following problem does occur when i used `carthage update` 
### xcodebulid Output

```
A shell task (/usr/bin/xcrun xcodebuild -project /Users/donnieyi/Workspace/CampusAssistant/CampusAssistant-iOS/Carthage/Checkouts/StatefulViewController/Example.xcodeproj -scheme StatefulViewController-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
```

Someone had this problem?

**Comment by aschuch** [comment]
Are you using Swift 3.0? 
With the new 3.0 release, `carthage update --no-use-binaries` seems to be working fine, can you please try again?

**Comment by savagegus** [comment]
I am seeing the same thing

`xcodebuild -version:` Xcode 8.2 Build version 8C38
`carthage version:` 0.18.1

`A shell task (/usr/bin/xcrun xcodebuild -project /Users/matt/src/cloudability/cloudability/Carthage/Checkouts/StatefulViewController/Example.xcodeproj -scheme StatefulViewController-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **`

**Comment by aschuch** [comment]
@savagegus I think this should be fixed by the 3.0.1 release yesterday, can you please try again?

**Comment by savagegus** [comment]
It resolved the issue for me, I tested both carthage and cocoapods.

**Comment by aschuch** [comment]
Cool, thanks for the heads up. I'll close this for now, feel free to open a new issue if something comes up again.
