### ISSUE TITLE
View when internet connection is unavailable.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [aschuch/StatefulViewController#38]
I want to show a view when internet connection not available. 

How do I achieve? I am using Alamofire for network API call.

**Comment by rowinShahi** [comment]
Alamofire.request("https://httpbin.org/get").responseJSON { response in
    if  let error  = response.result.value.error {
       endLoading(error: error)
   }else{
       endLoading(error: nil)
   }
}

**Comment by Rashesh-Bosamiya** [comment]
Ok, Thanks

**Comment by Rashesh-Bosamiya** [comment]
A logical help.


Actually, I have a common function for API calling. So, I want to display error view from central function. To the viewController where the request came.

Is it possible?
