### ISSUE TITLE
Clean checkout fails to build

### ISSUE THREAD

**Issue by jessedc** [aschuch/StatefulViewController#40]
Checking this project out the master branch or 3.0 tag does not compile under Xcode 8.2.

The compiler complains about SWIFT_VERSION and setting the value to 3.0 fixes the issue (https://github.com/Beanhunter/StatefulViewController/commit/3c9781ea208725e3029f36b301c4338d787e87f4) 

It looks like you have set the swift version to 3.0.1 intentionally, so I have raised this as an issue rather than a PR.

**Comment by aschuch** [comment]
This has been fixed in version 3.0.1.
