### ISSUE TITLE
** CLEAN FAILED **** BUILD FAILED **

### ISSUE THREAD

**Issue by pangpingfei** [aschuch/StatefulViewController#41]
xcode 8.2

*** Building scheme "StatefulViewController-iOS" in Example.xcodeproj
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /projects/PangPingfei/SuperDemo/SuperDemo/Carthage/Checkouts/StatefulViewController/Example.xcodeproj -scheme StatefulViewController-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by aschuch** [comment]
This has been fixed in version 3.0.1.
