### ISSUE TITLE
UIActivityIndicatorView Always on top left 

### ISSUE THREAD

**Issue by erickva** [aschuch/StatefulViewController#57]
UIActivityIndicatorView as loadingView Always on top left even when it's set with a larger frame, it is always small in the corner.
Is there a work around this? As the insets method applies for all the state views.

**Comment by aschuch** [comment]
Are you using the latest version from master?
Can you post some example code?

**Comment by erickva** [comment]
3.0, sure, in my test I am simply giving it a frame and assigning it to the loadingView:
```
let loading = UIActivityIndicatorView(frame: CGRect(x: 100, y: 100, width: 400, height: 400))
loading.startAnimating()
loadingView = loading
```

But regardless of the size of the View it is always in the top left corner:
<img width="137" alt="screen shot 2017-05-25 at 9 03 53 am" src="https://cloud.githubusercontent.com/assets/7539409/26429241/34bc3eaa-4129-11e7-9aec-e877327908bf.png">

**Comment by aschuch** [comment]
Hm, please try with the latest master branch, there are some changes in there that did not make it into an official release yet. Are you using a vanilla UIViewController or UITableViewController/UICollectionViewController?

**Comment by erickva** [comment]
It works perfectly with the master branch! Thank you very much aschuch!

**Comment by harishgonnabattula** [comment]
@aschuch  Can you release a new version from the master branch which will includes these changes?
