### ISSUE TITLE
Wrong state when network initially disabled

### ISSUE THREAD

**Issue by PatrykKaczmarek** [aschuch/StatefulViewController#6]
I discovered an "issue" when using StatefulViewController. When you turn off wi-fi and make request, `NetworkManager` will back with failure block before `viewWillAppearMethod`will be invoked. This makes for a short while `errorView` visible, then statefulMachine will change this view back to loading mode, what is untrue.

Here is code:
in `viewDidLoad()` I setup all states views:
```
emptyView = EmptyView(frame: view.frame)
errorView = ErrorView(frame: view.frame)
loadingView = LoadingView(frame: view.frame)
// and start loading data:
loadData()
```
`loadData()` method implementation:

```
func loadData() {
        
        if (lastState == .Loading) { return }
        
        startLoading()
        NetworkManager.sharedInstance.makeRequest({ (response) -> Void in
            /* do something with response*/
            self.endLoading()
        }, failure: { (error) -> () in
            self.endLoading(error: error)
        })
    }
```

Workaround:
Place `loadData()` method in `viewWillAppear()` after calling super. What force me to use `self.isMovingToParentViewController()` flag, when my controller hierarchy is expanded. Maybe you should consider to call:
```
// Make sure to stay in the correct state when transitioning
let isLoading = (currentState == .Loading)
let error: NSError? = (currentState == .Error) ? NSError() : nil
transitionViewStates(loading: isLoading, error: error, animated: false)
```
manually rather than clip it to `viewWillAppear()` ?

**Comment by aschuch** [comment]
Thanks for reporting. I have fixed this issue with the latest commits, you can now transition within `viewDidLoad` as well and the state does not change to loading anymore.
